### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by korochun**
Might have confused someone

### CODE REVIEW

**Comment by jlagarespo** [comment]
Afaik NASM uses getopt so it doesn't matter. For short options you can ignore that space, and it still runs just nicely. Indeed it compiles just nicely.
It is really weird that it failed for you though. Are you using the official QEMU branch, a fork by someone else, did you build it from source and modify it?

**Comment by korochun** [comment]
Indeed, after reinstalling NASM, it works. Don't know what happened there, but it works now. Thanks.

**Comment by jlagarespo** [comment]
That's extremly bizarre. Are you sure you weren't accidentally running the nasm command with a typo or something?

**Comment by korochun** [comment]
I think yes.

**Pull request closed without merging**
